import assert from 'node:assert/strict';
import {Journey,CLIPS} from './dist/journey.mjs';
import {existsSync,readFileSync} from 'node:fs';
import {uprightRotation} from './dist/orientation.mjs';
assert.equal(uprightRotation(0,1),0);
assert.equal(uprightRotation(0,-1),Math.PI);
assert.equal(uprightRotation(.4,-.8),Math.PI);
assert.equal(uprightRotation(1,.03,Math.PI),Math.PI,'Near-horizontal jitter retains correction');
assert.equal(uprightRotation(0,1,Math.PI),0,'Reacquired upright card clears correction');
assert.equal(uprightRotation(0,0,Math.PI),Math.PI,'Missing projection retains last valid rotation');
const j=new Journey();
const advance=(n,t)=>{for(let i=0;i<n;i++)j.update(.05,t);};
assert.equal(j.phase,'second');assert.equal(j.clip.start,1.15);
advance(100,5);assert.equal(j.time,0,'No playback before tracking');
j.visible=true;advance(3,2);assert.equal(j.ready,false,'Require stable card');advance(10,2);assert.ok(j.time>0);
j.visible=false;const time=j.time;advance(20,5);assert.equal(j.time,time,'Lost tracking pauses');
j.visible=true;advance(10,5);assert.ok(j.time>time,'Reacquisition resumes retained clip');
advance(10,9.85);assert.equal(j.phase,'done');advance(100,1.15);assert.equal(j.phase,'done','No automatic loop');
j.reset();assert.equal(j.phase,'second');assert.equal(j.time,0);assert.equal(j.ready,false);assert.equal(j.clip.start,1.15);
j.visible=true;advance(10,2);assert.ok(j.time>0,'Reset plays the same retained scene');
for(const file of ['assets/stickman-green.mp4','assets/blue-card.jpg','assets/blue-card.mind','assets/aframe.min.js','assets/mindar-image-aframe.prod.js'])assert.ok(existsSync('dist/'+file),file);
const source=readFileSync('dist/magic.js','utf8');assert.ok(source.includes('VideoTexture'));assert.ok(!source.includes('SphereGeometry'));console.log('PASS: single scene, stable tracking, pause/resume, completion, replay reset, orientation, video assets.');
